### ISSUE TITLE
Tokenize

### ISSUE THREAD

**Issue by ucasyjz** [beichenzbc/Long-CLIP#20]
Is there any difference in tokenizer between 'longclip.tokenize' and original clip tokenize in diffusers, can you give me some guidance, thanks. I change the length from 77 to 248 in original clip tokenizer config, but the output features embedding is different from the 'longclip.tokenize'

**Comment by beichenzbc** [comment]
there's no difference except from the positional embedding. The file ./model/simple_tokenizer.py didn't change. You may refer to ./model/longclip.py for further details.
