### ISSUE TITLE
Attention visualization in Long-CLIP?

### ISSUE THREAD

**Issue by zer0int** [beichenzbc/Long-CLIP#21]
I tried visualizing attention for text-image with Long-CLIP using a method that previously worked fine for the original CLIP (from captum.attr import visualization) including making modifications to model_longclip.py - however, gradient for blk.attn_probs remains None, no matter what I do.

If you could drop me a hint on where the issue might be, i.e. "yeah that's expected due to the triple ReLU, you'd have to do X", it would be tremendously helpful; thank you very much in advance!

**Comment by zer0int** [comment]
Fixed! 👍

![image](https://github.com/beichenzbc/Long-CLIP/assets/132047210/2a7bf440-4e95-49d1-82a8-b68268ff14c3)

**Comment by nwlxcdh255** [comment]
@zer0in
thello
Can you provide a visual code for learning?
Thank you very much.

**Comment by nwlxcdh255** [comment]
@zer0int
hello
Can you provide a visual code for learning?
Thank you very much.

**Comment by zer0int** [comment]
@nwlxcdh255 

I have uploaded the code to my fork of Long-CLIP:

[https://github.com/zer0int/Long-CLIP](https://github.com/zer0int/Long-CLIP)

See the update from 31/May/2024 for details:
```
Simply use runall-longclip-explain.py to batch processes
```

Basically, you just need to put images into an "IMG_IN" subfolder, run the script, and wait.
It will get CLIP's "opinion" [texts] about the images (gradient ascent), then compute all attention visualizations for what CLIP was "looking at" as it predicted [text] - and dump everything in subfolders. =)

Hope that is useful for you!

**Comment by nwlxcdh255** [comment]
@zer0int
Thank you very much for your reply.
Your reply is very useful.
I will try to learn.
