### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by jacksonwu09** [beichenzbc/Long-CLIP#22]
<img width="742" alt="image" src="https://github.com/beichenzbc/Long-CLIP/assets/69404310/e78df110-ef4a-4662-bc88-5767f53f1e93">

在运行代码时出现这样的错误，运行clip是可以的，您有遇到过这样的问题吗

**Comment by beichenzbc** [comment]
您好，很抱歉，我们修改DDP后没有及时更新demo，现在的demo应该可以运行
