### ISSUE TITLE
Evaluation code for long-caption text-image retrieval.

### ISSUE THREAD

**Issue by lygsbw** [beichenzbc/Long-CLIP#24]
Is there any plan to release the evaluation code for long-caption text-image retrieval?

**Comment by beichenzbc** [comment]
We have release the evaluation code for Urban-1k in eval/retrieval/urban1k.py.

**Comment by zimenglan-sysu-512** [comment]
hi @beichenzbc can u give me a help how to get `data/flickr/results_20130124.token` file?

**Comment by beichenzbc** [comment]
This is the official link https://shannon.cs.illinois.edu/DenotationGraph/data/index.html

**Comment by zimenglan-sysu-512** [comment]
thanks
