### ISSUE TITLE
Does the input size increases?

### ISSUE THREAD

**Issue by lucasjinreal** [beichenzbc/Long-CLIP#31]
Does the input size increases?

**Comment by beichenzbc** [comment]
The image preprocessors are the same as CLIP.
The text can be longer to 248 tokens.

**Comment by lucasjinreal** [comment]
Why not consider train a input resolution of 386 or 448 same as siglip does? So that this can be useful in Multimodal LLMs

**Comment by beichenzbc** [comment]
Thanks for your valuable advice. Our current code is based on CLIP, which has a maximum resolution of 336. We will consider training a higher resolution.
