### ISSUE TITLE
Please provide weight file with Baidu Cloud .

### ISSUE THREAD

**Issue by TheGreatTreatsby** [beichenzbc/Long-CLIP#32]
Hello, author. As we all know, a considerable number of domestic researchers have difficulty logging on to the Huggingface. So could you provide a weighted Baidu cloud file?

**Comment by beichenzbc** [comment]
https://pan.baidu.com/s/1JOVi7YLw79Ca-mBDUEaC_A
Code: jjse

**Comment by TheGreatTreatsby** [comment]
thx

> https://pan.baidu.com/s/1JOVi7YLw79Ca-mBDUEaC_A Code: jjse
