### ISSUE TITLE
微调LongClip

### ISSUE THREAD

**Issue by nimtecv** [beichenzbc/Long-CLIP#34]
尊敬的研究人员：
        我想用自己的数据集微调您的LongClip，但是发现有点无从下手，真诚的希望您能给与一点点帮助。
万分感谢

**Comment by beichenzbc** [comment]
您好，请问您能描述一下您碰到的问题吗

**Comment by nimtecv** [comment]
![image](https://github.com/beichenzbc/Long-CLIP/assets/158031260/af929eae-2fc7-4447-a825-bc00b09f61f7)
![image](https://github.com/beichenzbc/Long-CLIP/assets/158031260/af929eae-2fc7-4447-a825-bc00b09f61f7)
我zai在train中将模型加载为预训练好的模型，用我的数据集训练，torch.save(self.model.state_dict(), 'E:/XM/Long-CLIP-main/checkpoints/' + name)通过这个进行保存后，我想将他用到别的地方，但是一直无法加载

**Comment by beichenzbc** [comment]
有什么报错呢

**Comment by nimtecv** [comment]
你好 问题解决啦 谢谢
