### ISSUE TITLE
how to fine-tune LongCLIP on a single-node, single-GPU setup

### ISSUE THREAD

**Issue by YiguoHe** [beichenzbc/Long-CLIP#36]
Hello, I would like to ask how to fine-tune LongCLIP on a single-node, single-GPU setup. I attempted to fine-tune LongCLIP on my single-node, single-GPU, but encountered many errors related to distributed training that I couldn't resolve. Could you provide some guidance or examples for fine-tuning LongCLIP on a single-node, single-GPU? Thank you very much.

**Comment by beichenzbc** [comment]
Delete all the DDP code including DDP setup, DDP dataloader and all gather function.

**Comment by YiguoHe** [comment]
> Delete all the DDP code including DDP setup, DDP dataloader and all gather function.

thank you very much ! Looks like it worked.Best wishes!

**Comment by zimenglan-sysu-512** [comment]
@YiguoHe can u show the modify code how to train in single gpu? thanks.
