### ISSUE TITLE
How to use long clip in diffusers?

### ISSUE THREAD

**Issue by SnailForce** [beichenzbc/Long-CLIP#37]
And I want to know how to use long clip as Plug-and-Play in Image Generation?

**Comment by beichenzbc** [comment]
We will release a demo using LongCLIP in SDXL in a few days.

**Comment by SnailForce** [comment]
> We will release a demo using LongCLIP in SDXL in a few days.
Can you share the demo generated using sd1.5 mentioned in the paper for reference?

**Comment by snailforceG** [comment]
When will the code be released about the demo using LongCLIP in SDXL?

**Comment by CoolLifeG** [comment]
When will the code be released about  using LongCLIP in SDXL?
