### ISSUE TITLE
How to process text longer than 248?

### ISSUE THREAD

**Issue by ZihaoZheng98** [beichenzbc/Long-CLIP#38]
Could you please give an example of how to change the code? Many thanks.

**Comment by beichenzbc** [comment]
This model can't handle the text longer than 248. You may finetune your own Long-CLIP model for longer text.
Specifically, you need to modify 'load_from_clip' function in 'model/longclip.py'. You may adopt a larger interpolation ratio (recommended) or lowers the keep_len.
Besides, there're other small points like the shape of 'mask1' and 'mask2' in 'model/model_longclip.py' need to be changed. These are simple.

**Comment by SDaoer** [comment]
Why is there a limit on token length? My understanding is that during the pre-training of the CLIP model, positional encoding was only done for a length of 77 tokens. The model does not have prior knowledge of positional encodings beyond this length. For longer token sequences, giving a larger interpolation ratio accordingly is, as I understand it, to make the model pay more attention to the tokens in the later positions. Thanks for your enlightening work. I wonder if my understanding is correct?

**Comment by beichenzbc** [comment]
the positional embedding is directly added to the input embeddings, so the tokenizer will truncate the tokens longer than 77 in original clip since the positional embedding shape is (77, xxx)
