### ISSUE TITLE
the effect of different values of  'alpha' in loss 

### ISSUE THREAD

**Issue by YiguoHe** [beichenzbc/Long-CLIP#39]
Hello!
The pseudo-code of your fine-tuning process shows that 'the total loss =loss fine + alpha * loss_coarse'. Have you ever studied the effect of different values of this 'alpha' parameter?
thank you!
Best wishes!

**Comment by beichenzbc** [comment]
We made some ablations on alpha. The result is similar for alpha=0.1 or alpha=0.2.

**Comment by YiguoHe** [comment]
> We made some ablations on alpha. The result is similar for alpha=0.1 or alpha=0.2.

Thank you very much!
