### ISSUE TITLE
Is there any plans to release the training code and data?

### ISSUE THREAD

**Issue by RyanHuangNLP** [beichenzbc/Long-CLIP#4]
1.Is the training data could generate by mllm, get the dense caption?
2.how to select the training data, simple image is hard to generate long caption

**Comment by beichenzbc** [comment]
The training data is from ShareGPT4V, you could refer to this link: https://sharegpt4v.github.io/

We will release the training code soon

**Comment by BIGBALLON** [comment]
@beichenzbc I'm Looking forward to the open-sourcing of the training code. 

By the way, will the urban-200 evaluation set be open-sourced? This long caption evaluation dataset is significant.
Thank you again for this work.

**Comment by beichenzbc** [comment]
Thanks for recoginition. The training code has been released. We will open-source our urban-200 evaluation set, but it may take some time.
