### ISSUE TITLE
model

### ISSUE THREAD

**Issue by ucasyjz** [beichenzbc/Long-CLIP#40]
where torch.distributed.nn.all_gather in model_longclip.py 453

**Comment by beichenzbc** [comment]
sorry, i don't understand your question

**Comment by ucasyjz** [comment]
> sorry, i don't understand your question

Thanks, I have solved the problem by adding 'functional' as 'nn.' in 453 rows in model_longclip.py

**Comment by XLMore** [comment]
> > sorry, i don't understand your question
> 
> Thanks, I have solved the problem by adding 'functional' as 'nn.' in 453 rows in model_longclip.py

Hello,I meet the same problem, Can you tell me what does line 453 look like after your change?

**Comment by XLMore** [comment]
> > sorry, i don't understand your question
> 
> Thanks, I have solved the problem by adding 'functional' as 'nn.' in 453 rows in model_longclip.py

Hello, I met the same problem,can you tell me how did you fix it?

**Comment by nanamma** [comment]
> > > sorry, i don't understand your question
> > 
> > 
> > Thanks, I have solved the problem by adding 'functional' as 'nn.' in 453 rows in model_longclip.py
> 
> Hello, I met the same problem,can you tell me how did you fix it?

my torch version is 2.1.2
just change the codes like this
````python
        # image_feat_all_long = torch.cat(torch.distributed.nn.all_gather(image_features_long), dim=0) #gather with grad
        # image_features_all_short = torch.cat(torch.distributed.nn.all_gather(image_features_short), dim=0)
        # text_feat_all_long = torch.cat(torch.distributed.nn.all_gather(text_features_long), dim=0)
        # text_feat_all_short = torch.cat(torch.distributed.nn.all_gather(text_features_short), dim=0)
        image_feat_all_long_      = [torch.ones_like(image_features_long)]*torch.distributed.get_world_size() #list
        image_features_all_short_ = [torch.ones_like(image_features_short)]*torch.distributed.get_world_size()
        text_feat_all_long_       = [torch.ones_like(text_features_long)]*torch.distributed.get_world_size()
        text_feat_all_short_      = [torch.ones_like(text_features_short)]*torch.distributed.get_world_size()
        torch.distributed.all_gather(image_feat_all_long_,image_features_long) #gather with grad
        torch.distributed.all_gather(image_features_all_short_,image_features_short)
        torch.distributed.all_gather(text_feat_all_long_,text_features_long)
        torch.distributed.all_gather(text_feat_all_short_,text_features_short)
        image_feat_all_long      = torch.cat(image_feat_all_long_, dim=0) #cat
        image_features_all_short = torch.cat(image_features_all_short_, dim=0)
        text_feat_all_long       = torch.cat(text_feat_all_long_, dim=0)
        text_feat_all_short      = torch.cat(text_feat_all_short_, dim=0)
````
