### ISSUE TITLE
can put ShareGPT4V dataset into huggingface?

### ISSUE THREAD

**Issue by zimenglan-sysu-512** [beichenzbc/Long-CLIP#43]
can put ShareGPT4V dataset into huggingface? so that we can directly download them.

**Comment by beichenzbc** [comment]
You may refer to this link https://huggingface.co/datasets/Lin-Chen/ShareGPT4V

**Comment by zimenglan-sysu-512** [comment]
get it. thanks. another question: is is possible to run the train.py without using sam dataset, since sam dataset is too big to download? will it hurt the performace?

**Comment by beichenzbc** [comment]
we didn't try it.

**Comment by zimenglan-sysu-512** [comment]
get it
