### ISSUE TITLE
PCA In the inference stage.

### ISSUE THREAD

**Issue by exiawsh** [beichenzbc/Long-CLIP#53]
Hello, during the training phase, PCA is used to extract rough features and align them with short text. Why is PCA not used for short texts during the testing phase? Will this result in inconsistent training and testing?

**Comment by beichenzbc** [comment]
That's a good question. The PCA is used to require the model not only capture complete information, but also can recognize which information is the most important part during training.

In testing, if the feature can contain complete information and the corresponding importance, it can do both long-text and short-text tasks well.

**Comment by exiawsh** [comment]
Got it thanks.
