### ISSUE TITLE
Summarized short captions of ShareGPT4v for training

### ISSUE THREAD

**Issue by ivonajdenkoska** [beichenzbc/Long-CLIP#59]
Hi, thanks for the great work!

Can you explain how you obtained the summarized short captions of ShareGPT4v for training? 

The paper mentions the usage of these short captions, but we cannot find them in the repo or in HugginngFace (https://huggingface.co/datasets/Lin-Chen/ShareGPT4V). Can you release them? Thanks a lot in advance!

**Comment by beichenzbc** [comment]
Thanks, that's a good question.
ShareGPT4v only contains long captions. However, the first sentence is usually a short summary sentence like 'the image showcases ......'. Therefore, we can take the first sentence as the short caption.
