### ISSUE TITLE
显存占用问题

### ISSUE THREAD

**Issue by Lil-CC** [beichenzbc/Long-CLIP#61]
默认的单卡batch_size = 128，是在什么显卡上训练的呢？

**Comment by beichenzbc** [comment]
A100

**Comment by Lil-CC** [comment]
运行flickr30k.py，在32G显卡上会爆显存，这应该怎么办啊

**Comment by beichenzbc** [comment]
把22到28行的常数20改大一点

**Comment by Lil-CC** [comment]
ShareGPT4V、ImageNet-O、ImageNet-v2的验证代码会release嘛

**Comment by beichenzbc** [comment]
shareGPT4v的代码在训练里面有，imagenet-o和imagenet-v2的代码和imagenet基本一致，把数据源改一下就行
