### ISSUE TITLE
Extra memory being used in training loop

### ISSUE THREAD

**Issue by rsomani95** [beichenzbc/Long-CLIP#63]
This line https://github.com/beichenzbc/Long-CLIP/blob/9308e5e5ed2156e2465d490485101069f86dbf26/train/train.py#L155 create a clone of the image tensors that isn't being used. Removing this should allow for a much larger batch size. 

I see below that this chunk that used `images_short` has now been commented out:
https://github.com/beichenzbc/Long-CLIP/blob/9308e5e5ed2156e2465d490485101069f86dbf26/train/train.py#L162-L169

**Comment by beichenzbc** [comment]
Oh, thanks for pointing out this.
