### ISSUE TITLE
About maintaining the retrieval ability of short text after fine-tuning cn_clip

### ISSUE THREAD

**Issue by XA-hyy** [beichenzbc/Long-CLIP#64]
Hello author, I would like to ask, can I maintain the retrieval ability of clip on short text by only using the KPS method mentioned in the paper and loading clip weights on short text for training (according to the comparative experiment in Table 5 of the paper, KPS should play a more important role in maintaining the ability of short text). At present, I have integrated the KPS method into cn_clip, randomly selected a small amount of data disclosed by cn_clip for fine-tuning, and found that the general retrieval ablility of short text is still declining. I wonder if it is necessary to use long text data with more detailed descriptions for training to be useful? Can you give me some advice in this regard? Thank you.

**Comment by beichenzbc** [comment]
We didn't try cn_clip, which may be a bit different from clip. According to our experience, interpolating will cause degradation of short-text capability, and sufficient long text data may make up for this degradation. So leveraging more high-quality data in fine-tuning may be helpful.

Moreover, you may also try a smaller value of interpolation ratio (4 -> 3) or a larger keeping length (20 -> 30). However, this will lowers the maximum length supported, which is a trade-off according to your own application.

**Comment by XA-hyy** [comment]
Thanks for your reply, i will have a try
