### ISSUE TITLE
PCA numerically appears to do very little / nothing

### ISSUE THREAD

**Issue by damian0815** [beichenzbc/Long-CLIP#68]
We're implementing Long-CLIP ourselves and have noticed something unexpected with PCA. At 32 PCA dimensions the difference between the original `image_features` and the PCA-simplified `reduced_image_features` is numerically insignificant (<1e-6 difference across individual dimensions, <2e-3 difference abs sum). Computing the loss, there's very little difference between the text-image loss with the full image vs text-image loss with the PCA reduced image, even if the number of PCA dimensions is pulled all the way down to 2:

```
def compute_image_feature_delta(image_features, pca_dim):
    reduced_image_features = PCA(image_features, PCA_dim=pca_dim)
    return torch.abs(image_feautres - reduced_image_features).sum()

image_features = torch.randn([3, 1280], generator=torch.Generator().manual_seed(0))
print(compute_image_feature_delta(image_features, pca_dim=32)) # 0.0014
print(compute_image_feature_delta(image_features, pca_dim=16)) # 0.0014 
print(compute_image_feature_delta(image_features, pca_dim=8)) # 0.0014
print(compute_image_feature_delta(image_features, pca_dim=4)) # 0.0014
print(compute_image_feature_delta(image_features, pca_dim=2)) # 0.0014
```

We know from prior experience that a CLIP embedding with this small total delta is effectively identical. It appears like PCA with 32 dimensions is not contributing in any meaningful way to the output - it's effectively the same as running cross-entropy loss on the original image features. 

Are we missing something?

**Comment by beichenzbc** [comment]
Perhaps you may try a larger batch size or a lower PCA dimension.
