### ISSUE TITLE
Long caption-image retrieval with CLIP tokenizers?

### ISSUE THREAD

**Issue by ivonajdenkoska** [beichenzbc/Long-CLIP#69]
Hi, thanks again for your cool work!

I was looking into the long caption-image retrieval with Urban1k dataset. The tokenizers used by CLIP models usually tokenize the sentence into 77 tokens. I'm wondering if you modified this behavior to tokenize the full sentence into more than 77 tokens, basically without truncation? Thanks in advance!

**Comment by beichenzbc** [comment]
longclip.tokenize can tokenize up to 248 tokens.

**Comment by ivonajdenkoska** [comment]
Thanks for your answer. Could you briefly explain how you changed the original CLIP tokenizer which tokenizes up to 77 tokens?

**Comment by beichenzbc** [comment]
We change the default context_length in clip.py or longclip.py. You may refer to https://github.com/beichenzbc/Long-CLIP/blob/main/model/longclip.py for further detailes.
