### ISSUE TITLE
Failed to try with SDXL

### ISSUE THREAD

**Issue by ziyye** [beichenzbc/Long-CLIP#7]
SDXL have two clip text encoders: CLIP-L and CLIP-G.
I replace the original CLIP-L text encoder with long-CLIP-L, then padding embeddings of original CLIP-G to length 248 (248 is the length of long-clip-L embeddings) and concat those embeddings with embeddings from long-CLIP-L. But the generated images not good.
Anyone tried long-clip with SDXL, should it work?

**Comment by GongXinyuu** [comment]
> SDXL have two clip text encoders: CLIP-L and CLIP-G. I replace the original CLIP-L text encoder with long-CLIP-L, then padding embeddings of original CLIP-G to length 248 (248 is the length of long-clip-L embeddings) and concat those embeddings with embeddings from long-CLIP-L. But the generated images not good. Anyone tried long-clip with SDXL, should it work?

Hi @ziyye would you mind sharing some images generated by your SDXL + long-CLIP-L implementation?

**Comment by ziyye** [comment]
Thanks for your reply! Here are some images generated: 
<img width="540" alt="image" src="https://github.com/beichenzbc/Long-CLIP/assets/38159569/e26da7a6-cae9-4ac8-84c5-fef00ba9e27f">
<img width="534" alt="image" src="https://github.com/beichenzbc/Long-CLIP/assets/38159569/927691f8-a53e-4c47-8165-7f3d3ae9b54a">
<img width="535" alt="image" src="https://github.com/beichenzbc/Long-CLIP/assets/38159569/7fff7528-0394-4062-90de-9c901f7718d1">
<img width="537" alt="image" src="https://github.com/beichenzbc/Long-CLIP/assets/38159569/e57ba7cc-5828-49a2-a175-c13d62df23a7">

**Comment by ppeterpp** [comment]
sdxl seems to use 'penultimate text encoder outputs', have you also used the same output from the long-clip?

**Comment by plastic0313** [comment]
> Thanks for your reply! Here are some images generated: <img alt="image" width="540" src="https://private-user-images.githubusercontent.com/38159569/319016575-e26da7a6-cae9-4ac8-84c5-fef00ba9e27f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1ODAwODUsIm5iZiI6MTcxMjU3OTc4NSwicGF0aCI6Ii8zODE1OTU2OS8zMTkwMTY1NzUtZTI2ZGE3YTYtY2FlOS00YWM4LTg0YzUtZmVmMDBiYTllMjdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDEyMzYyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4Yjk1ZjhjMjc3MTJmNWUzNTcwMjc2ZTI0NThlYWI5NjE4ZDNmMGMyNzgzNzY1OWZjMTY1MmVmYWU4Y2RkNzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZVyRG7DLh9r8zxvUb6HbwIhzOd6wChJGMUL7NHsP54M"> <img alt="image" width="534" src="https://private-user-images.githubusercontent.com/38159569/319016748-927691f8-a53e-4c47-8165-7f3d3ae9b54a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1ODAwODUsIm5iZiI6MTcxMjU3OTc4NSwicGF0aCI6Ii8zODE1OTU2OS8zMTkwMTY3NDgtOTI3NjkxZjgtYTUzZS00YzQ3LTgxNjUtN2YzZDNhZTliNTRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDEyMzYyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwMTYxMWQzNmRjYWNlMjRhMTA4OGJiMGYzZmRhNjkyNTRlMjQxZTIzMDZmOTY4YzhkYTc1MmIzZDkyMmRhNWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6i-s4pWcujPJP4Ld9bMj44E7aFfjFB6y4kRkqYpCXOk"> <img alt="image" width="535" src="https://private-user-images.githubusercontent.com/38159569/319016775-7fff7528-0394-4062-90de-9c901f7718d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1ODAwODUsIm5iZiI6MTcxMjU3OTc4NSwicGF0aCI6Ii8zODE1OTU2OS8zMTkwMTY3NzUtN2ZmZjc1MjgtMDM5NC00MDYyLTkwZGUtOWM5MDFmNzcxOGQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDEyMzYyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzYjBhODBkMmU1MDU0OWRmYmEzODM0ODkwMjdmNmJkNWNmNTU2Mzc4MmIxOTNiMDdiZDJhZGI1Y2IyOTc5OTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A-tMy83-_X6aP3hCs4vJoargOMIQB93RpK6PvEWd-i4"> <img alt="image" width="537" src="https://private-user-images.githubusercontent.com/38159569/319016796-e57ba7cc-5828-49a2-a175-c13d62df23a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1ODAwODUsIm5iZiI6MTcxMjU3OTc4NSwicGF0aCI6Ii8zODE1OTU2OS8zMTkwMTY3OTYtZTU3YmE3Y2MtNTgyOC00OWEyLWExNzUtYzEzZDYyZGYyM2E3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDEyMzYyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3NDMzZmEzODc0ZGUwOTE4YmFlMGI5NWZjMDA1MTg5ODYzMzg1M2RhNjBjNDA1ZjlhMzI2ODY5YTVjZDUwMTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9fEbMqKe3pH9c9zrO4TrvCWwMRL48rkZQXWG9Qully4">

I have the same problem. Have you solved it?

**Comment by zer0int** [comment]
Same. I went as far as stripping down the prompt to just "cat", and I got this:

![something2ddd](https://github.com/beichenzbc/Long-CLIP/assets/132047210/56366061-b4ef-41b9-80e4-a3ad14a7d212)

Just why?! [😂](https://emojipedia.org/face-with-tears-of-joy)

I'll update when and if I get it working better. [🙃](https://emojipedia.org/upside-down-face)

**Comment by zer0int** [comment]
This actually works really well: [https://github.com/SeaArtLab/ComfyUI-Long-CLIP](https://github.com/SeaArtLab/ComfyUI-Long-CLIP)
