### ISSUE TITLE
微调LongCLIP-L时报错

### ISSUE THREAD

**Issue by XLMore** [beichenzbc/Long-CLIP#70]
你好，我使用自己构建的数据集微调Long-CLIP-L时，发生以下错误，请问是什么混合精度设置有问题吗？
Traceback (most recent call last):
File "train.py", line 365, in <module>
trainer.train(resume=args.resume, warmup_length=args.warmup_length)
File "train.py", line 272, in train
self.train_epoch(train_loader, epoch, start_iter=resume_iter)
File "train.py", line 174, in train_epoch
self.scaler.step(self.optimizer)
File "/opt/conda/lib/python3.8/site-packages/torch/cuda/amp/grad_scaler.py", line 334, in step
self.unscale_(optimizer)
File "/opt/conda/lib/python3.8/site-packages/torch/cuda/amp/grad_scaler.py", line 279, in unscale_
optimizer_state["found_inf_per_device"] = self._unscale_grads_(optimizer, inv_scale, found_inf, False)
File "/opt/conda/lib/python3.8/site-packages/torch/cuda/amp/grad_scaler.py", line 207, in _unscale_grads_
raise ValueError("Attempting to unscale FP16 gradients.")
ValueError: Attempting to unscale FP16 gradients.
Traceback (most recent call last):
File "train.py", line 365, in <module>
trainer.train(resume=args.resume, warmup_length=args.warmup_length)
File "train.py", line 272, in train
self.train_epoch(train_loader, epoch, start_iter=resume_iter)
File "train.py", line 174, in train_epoch
self.scaler.step(self.optimizer)
File "/opt/conda/lib/python3.8/site-packages/torch/cuda/amp/grad_scaler.py", line 334, in step
self.unscale_(optimizer)
File "/opt/conda/lib/python3.8/site-packages/torch/cuda/amp/grad_scaler.py", line 279, in unscale_
optimizer_state["found_inf_per_device"] = self._unscale_grads_(optimizer, inv_scale, found_inf, False)
File "/opt/conda/lib/python3.8/site-packages/torch/cuda/amp/grad_scaler.py", line 207, in _unscale_grads_
raise ValueError("Attempting to unscale FP16 gradients.")
ValueError: Attempting to unscale FP16 gradients.

**Comment by beichenzbc** [comment]
我们没碰到过，应该是with torch.cuda.amp.autocast():的问题，可以选择把这一行删掉，代价就是训练显存会上升，速度会降低

**Comment by XLMore** [comment]
> 我们没碰到过，应该是with torch.cuda.amp.autocast():的问题，可以选择把这一行删掉，代价就是训练显存会上升，速度会降低

我load是LongCLIP-L,看了下加载后模型是fp16的，转成fp32之后可以了，谢谢

**Comment by beichenzbc** [comment]
没事没事

**Comment by Graysonggg** [comment]
> 你好，我使用自己构建的数据集微调Long-CLIP-L时，发生以下错误，请问是什么混合精度设置有问题吗？ Traceback (most recent call last): File "train.py", line 365, in trainer.train(resume=args.resume, warmup_length=args.warmup_length) File "train.py", line 272, in train self.train_epoch(train_loader, epoch, start_iter=resume_iter) File "train.py", line 174, in train_epoch self.scaler.step(self.optimizer) File "/opt/conda/lib/python3.8/site-packages/torch/cuda/amp/grad_scaler.py", line 334, in step self.unscale_(optimizer) File "/opt/conda/lib/python3.8/site-packages/torch/cuda/amp/grad_scaler.py", line 279, in unscale_ optimizer_state["found_inf_per_device"] = self._unscale_grads_(optimizer, inv_scale, found_inf, False) File "/opt/conda/lib/python3.8/site-packages/torch/cuda/amp/grad_scaler.py", line 207, in _unscale_grads_ raise ValueError("Attempting to unscale FP16 gradients.") ValueError: Attempting to unscale FP16 gradients. Traceback (most recent call last): File "train.py", line 365, in trainer.train(resume=args.resume, warmup_length=args.warmup_length) File "train.py", line 272, in train self.train_epoch(train_loader, epoch, start_iter=resume_iter) File "train.py", line 174, in train_epoch self.scaler.step(self.optimizer) File "/opt/conda/lib/python3.8/site-packages/torch/cuda/amp/grad_scaler.py", line 334, in step self.unscale_(optimizer) File "/opt/conda/lib/python3.8/site-packages/torch/cuda/amp/grad_scaler.py", line 279, in unscale_ optimizer_state["found_inf_per_device"] = self._unscale_grads_(optimizer, inv_scale, found_inf, False) File "/opt/conda/lib/python3.8/site-packages/torch/cuda/amp/grad_scaler.py", line 207, in _unscale_grads_ raise ValueError("Attempting to unscale FP16 gradients.") ValueError: Attempting to unscale FP16 gradients.

你好，请问您用自己的数据集微调longClip时的计算资源是怎样的，4张3090够不够，谢谢
