### ISSUE TITLE
Reason for tokenizing to 77*4-60 tokens

### ISSUE THREAD

**Issue by ivonajdenkoska** [beichenzbc/Long-CLIP#72]
Hi, thanks again for the cool work! 

I was wondering why the tokenizer is tokenizing to 248 tokens i.e. **77*4-60** (as I can see in the code here: https://github.com/beichenzbc/Long-CLIP/blob/main/model/longclip.py#L313)? Why is 60 subtracted from 77*4? Thanks in advance!

**Comment by beichenzbc** [comment]
The first 20 out of 77 token is kept, so the maximum token is 20 + (77-20) * 4 = 248
