### ISSUE TITLE
About the ckpt

### ISSUE THREAD

**Issue by WayneTomas** [beichenzbc/Long-CLIP#73]
Thanks for your great work! May I ask if you can release a ViT-L-336 ckpt?

**Comment by beichenzbc** [comment]
Thanks for your recognition, you may refer to this link https://huggingface.co/BeichenZhang/LongCLIP-L-336px/tree/main

**Comment by WayneTomas** [comment]
> Thanks for your recognition, you may refer to this link https://huggingface.co/BeichenZhang/LongCLIP-L-336px/tree/main

Wow！！Thank you for your valuable contribution; it's truly appreciated!
