### ISSUE TITLE
How to pass the embeddings for KSampler?

### ISSUE THREAD

**Issue by vikas784** [beichenzbc/Long-CLIP#77]
Hi okay so see, I  am trying to make the pipeline for connecting your embeddings to the KSampler of ComfyUI, okay so see what I m doing I m using your encode_prompt.py file for getting positive and negative embeddings and that use that embeddings for Ksampler of ComfyUI, so see generally when we use ClipTextEncodeSDXL the embeddings which shape which we get is,

1. ClipTextEncodeSDXL
Positive Embeddings = (1,77,2048)
Pooled Positive Embedidings = (1,1280)
Negative Embeddings = (1,77,2048) 
Pooled Negative Embeddings = (1,1280)

2. Encode_Prompt(Long Clip)
Positive Embeddings = (1,248,2048)
Pooled Positive Embedidings = (1,1280)
Negative Embeddings = (1,248,2048) 
Pooled Negative Embeddings = (1,1280) 

How should I connect it?

**Comment by beichenzbc** [comment]
Sorry I'm not familiar with ComfyUI and ComfyUI-LongCLIP is not developed by us. You may ask https://github.com/SeaArtLab/ComfyUI-Long-CLIP for help.
