### ISSUE TITLE
the random 1k ShareGPT4V validation set

### ISSUE THREAD

**Issue by Arsiuuu** [beichenzbc/Long-CLIP#8]
Thanks for the great work! Could you please share the random 1k ShareGPT4V validation set split?
![image](https://github.com/beichenzbc/Long-CLIP/assets/72386089/965e25d4-cdaf-4e81-8626-5b3cf50f9438)

**Comment by MajorDavidZhang** [comment]
I checked their code. The 1k validation set is the first 1k instances in share-captioner_coco_lcs_sam_1246k_1107.json

**Comment by Arsiuuu** [comment]
Thanks for your reply~
