### ISSUE TITLE
Empty txt file in huggingface urban-1k

### ISSUE THREAD

**Issue by wasabipretzel** [beichenzbc/Long-CLIP#84]
Hi, thank you for wonderful work and data release!

I have been working with the Urban1K dataset in huggingface and noticed that the file caption/592.txt is empty. 

Before proceeding, I wanted to confirm whether this is intentional or an oversight.

Could you clarify if this is expected behavior or if the file should contain some content?

**Comment by beichenzbc** [comment]
Thanks for pointing out this! The caption is missing and we have updated it into the huggingface dataset page.

**Comment by wasabipretzel** [comment]
Thank you for the quick response! 

I can see the new version uploaded to Hugging Face has the missing captions filled in.
